apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
spec:
  selector:
    app: cicd-demo
  type: LoadBalancer       # Creates AWS ALB automatically
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
